build: false

for:
- branches:
    only:
      - /.*/
  environment:
    matrix:
      - PYTHON: "C:\\Python27"
        PYTHONVERSION: 2.7
        ARCHITECTURE: "i386"
        MINICONDA: "C:\\Miniconda"
        ENERGYPLUS_VERSION: "8.9.0"
        ENERGYPLUS_SHA: "40101eaafd"
      - PYTHON: "C:\\Python27-x64"
        PYTHONVERSION: 2.7
        ARCHITECTURE: "x86_64"
        MINICONDA: "C:\\Miniconda"
        ENERGYPLUS_VERSION: "8.9.0"
        ENERGYPLUS_SHA: "40101eaafd"
      - PYTHON: "C:\\Python37"
        PYTHONVERSION: 3.7
        ARCHITECTURE: "i386"
        MINICONDA: "C:\\Miniconda37"
        ENERGYPLUS_VERSION: "8.9.0"
        ENERGYPLUS_SHA: "40101eaafd"
      - PYTHON: "C:\\Python37-x64"
        PYTHONVERSION: 3.7
        ARCHITECTURE: "x86_64"
        MINICONDA: "C:\\Miniconda37-x64"
        ENERGYPLUS_VERSION: "8.9.0"
        ENERGYPLUS_SHA: "40101eaafd"

-
  branches:
    only:
      - master
  environment:
    matrix:
      - PYTHON: "C:\\Python27"
        PYTHONVERSION: 2.7
        ARCHITECTURE: "i386"
        MINICONDA: "C:\\Miniconda"
        ENERGYPLUS_VERSION: "8.9.0"
        ENERGYPLUS_SHA: "40101eaafd"
      - PYTHON: "C:\\Python27-x64"
        PYTHONVERSION: 2.7
        ARCHITECTURE: "x86_64"
        MINICONDA: "C:\\Miniconda"
        ENERGYPLUS_VERSION: "8.9.0"
        ENERGYPLUS_SHA: "40101eaafd"

      - PYTHON: "C:\\Python37"
        PYTHONVERSION: 3.7
        ARCHITECTURE: "i386"
        MINICONDA: "C:\\Miniconda37"
        ENERGYPLUS_VERSION: "8.8.0"
        ENERGYPLUS_SHA: "7c3bbe4830"
      - PYTHON: "C:\\Python37-x64"
        PYTHONVERSION: 3.7
        ARCHITECTURE: "x86_64"
        MINICONDA: "C:\\Miniconda37-x64"
        ENERGYPLUS_VERSION: "8.8.0"
        ENERGYPLUS_SHA: "7c3bbe4830"
      - PYTHON: "C:\\Python37"
        PYTHONVERSION: 3.7
        ARCHITECTURE: "i386"
        MINICONDA: "C:\\Miniconda37"
        ENERGYPLUS_VERSION: "8.9.0"
        ENERGYPLUS_SHA: "40101eaafd"
      - PYTHON: "C:\\Python37-x64"
        PYTHONVERSION: 3.7
        ARCHITECTURE: "x86_64"
        MINICONDA: "C:\\Miniconda37-x64"
        ENERGYPLUS_VERSION: "8.9.0"
        ENERGYPLUS_SHA: "40101eaafd"

install:
  # set up Miniconda test environment
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda info -a
  - conda update -q conda
  - "conda create -n test-env python=%PYTHONVERSION% pytest lxml"
  - "activate test-env"

  - ECHO "Filesystem root:"
  - ps: "ls \"C:/\""

  - ECHO "Installed SDKs:"
  - ps: "ls \"C:/Program Files/Microsoft SDKs/Windows\""
  # install EnergyPlus
  - ECHO "Installing EnergyPlus"
  - ps: $env:ENERGYPLUS_INSTALL_VERSION = $env:ENERGYPLUS_VERSION -replace '\.','-'
  - ps: $env:ENERGYPLUS_DOWNLOAD_BASE_URL = "https://github.com/NREL/EnergyPlus/releases/download/v$env:ENERGYPLUS_VERSION"
  - ps: $env:ENERGYPLUS_DOWNLOAD_FILENAME = "EnergyPlus-$env:ENERGYPLUS_VERSION-$env:ENERGYPLUS_SHA-Windows-$env:ARCHITECTURE.exe"
  - ps: $env:ENERGYPLUS_DOWNLOAD_URL = "$env:ENERGYPLUS_DOWNLOAD_BASE_URL/$env:ENERGYPLUS_DOWNLOAD_FILENAME"

  - ps: "curl $env:ENERGYPLUS_DOWNLOAD_URL -OutFile $env:TMP\\$env:ENERGYPLUS_DOWNLOAD_FILENAME"
  - ps: "& $env:TMP\\$env:ENERGYPLUS_DOWNLOAD_FILENAME /S | Out-Null"

  - ps: echo $env:PYTHON

  # set the integration test environment variable
  - "SET EPPY_INTEGRATION=TRUE"
  # install eppy
  - "python setup.py install"

test_script:
  # Test command.
  - "python -m pytest eppy -v"
